name: Update Player Count

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Use the token here

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          HYPIXEL_API_KEY: ${{ secrets.HYPIXEL_API_KEY }}
        run: python script.py  # Change to your actual script filename

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add player_counts.csv punishment_stats.csv  # Both files
          git commit -m "Updated player count data" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/Knattekalle/Hypixel---Data.git
